### ISSUE TITLE
Windows path resolution

### ISSUE THREAD

**Issue by onikienko** [extend-chrome/js-react-boilerplate#2]
Unfortunately, #1 still here. Even with latest *rollup-plugin-chrome-extension* v3.5.4

To reproduce just clone this repo and add `import React from "react"` to the beginning of `src\content\index.js`.

There are no bundler errors anymore. But popup won't work and you will see the error:

> Failed to load resource: net::ERR_FILE_NOT_FOUND react.development-94e4b17c.js:1 

The content script won't work as well. With error: 

> Denying load of chrome-extension://nplphkojpiolefcbfafcnhehhoekkmll/Projects/experiments/js-react-boilerplate/chunks/react.development-94e4b17c.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

Looks like something with a path handling here. M on Windows...

**Comment by jacksteamdev** [comment]
@onikienko I'm not able to reproduce what you're describing. :disappointed: 

When I add the following to the content script...

```javascript
import React from 'react'
import { render } from 'react-dom'

console.log('content script')

const root = document.createElement('div')
root.id = 'root'
document.body.append(root)

render(<h1>Hello World</h1>, root)
```

You can see the Popup and "Hello World" halfway down the page. Everything seems to work! :smile_cat: 

![image](https://user-images.githubusercontent.com/23390212/110701327-a5c34180-81b6-11eb-843e-3edf5831f382.png)

If you could provide a minimum reproduction and some screenshots (any errors and also the dist folder contents), maybe we can get to the bottom of this problem.

**Comment by onikienko** [comment]
@jacksteamdev Thank you for your reply.

I created a simple repo to demonstrate the bug - https://github.com/onikienko/js-react-boilerplate-bug-demo

There is a screenshot with errors I have:

![image](https://user-images.githubusercontent.com/3234928/110758312-10c35580-8255-11eb-92a5-9925683395f6.png)


M running Windows 10. node.js v14.15.3. npm v6.14.9

**Comment by onikienko** [comment]
I was able to test this on Linux (Ubuntu). And it works there. 

So looks like the issue is on Windows. I suppose it related to path resolving.

**Comment by jacksteamdev** [comment]
@onikienko Thanks for the screenshots and repo! The problem is probably caused by this line:

https://github.com/extend-chrome/js-react-boilerplate/blob/65f8dd1769accdddea34b2fc7b6efb33abcbf53c/rollup.config.js#L17

The path segment separator would be [different for Windows](https://nodejs.org/api/path.html#path_path_sep). I tried flipping the separator on Linux, and got the same behavior from your screenshot.

I've pushed a commit that changes that line to this:

https://github.com/extend-chrome/js-react-boilerplate/blob/a86908bc0540c36b69817555a6c2cfd24b188606/rollup.config.js#L19

I don't have a Windows machine to try it out on, but hopefully this will fix it! :crossed_fingers:

**Comment by onikienko** [comment]
Hi, @jacksteamdev 
Thanks for your fixes. 
It fixes the popup but not fix the content script. Because generated manifes.json will have the wrong path in web_accessible_resource: 
![image](https://user-images.githubusercontent.com/3234928/111143907-0d023c80-858f-11eb-96ff-85c9da8af813.png)

The easiest way to fix it will be to replace https://github.com/extend-chrome/js-react-boilerplate/blob/a86908bc0540c36b69817555a6c2cfd24b188606/rollup.config.js#L19

with something like `chunkFileNames: 'chunk-[name]-[hash].js`. To avoid subfolders and wrong path resolution. 

Btw, it will be great to do not use `web_accessible_resources` in this case at all...

**Comment by jacksteamdev** [comment]
@onikienko Thanks for all your help! This seems to be a Rollup / `rollup-plugin-chrome-extension` issue. Apparently some Windows paths leak into the manifest.

The origin of that weird path in the manifest:

```
const path = require('path');

const string = path.join('foo', 'bar');
// Unix    => foo/bar
// Windows => foo\\bar
```

[This PR](https://github.com/extend-chrome/rollup-plugin-chrome-extension/pull/72) maps all script paths through through [`slash`](https://www.npmjs.com/package/slash) to fix this.
